{
    "app": "wide_image",
    "prompt": "Fantasy mountainous terrain with ancient ruins carved into cliffs, glowing crystals in the cave walls, flying dragons in the distance, dark clouds, dramatic fantasy lighting, concept art style, by Artgerm and WLOP",
    "negative_prompt": "",
    "num_inference_steps": 50,
    "guidance_scale": 7.5,
    "seed": 1,
    "gpu": 0,
    "sampling_method": "ddim",
    "model": "sd",
    "sd_path": "stabilityai/stable-diffusion-2-base",
    "ref_attention_end": 0.2,
    "mvd_end": 0.8,
    "save_top_dir": "./outputs",
    "tag": "wide_image",
    "save_dir_now": true,
    "log_step": 10,
    "eval_w": [
        0,
        10,
        20,
        30,
        40,
        50,
        60,
        70
    ],
    "eval_h": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
    ],
    "initialize_xt_from_zt": false,
    "window_stride": 8,
    "latent_instance_size": 64,
    "rgb_instance_size": 512,
    "panorama_height": 512,
    "panorama_width": 3072,
    "eval_pos": [
        0,
        128,
        256,
        384,
        512,
        640,
        768,
        896
    ]
}