{
    "app": "wide_image",
    "prompt": "The Great Wall of China snaking across rugged mountains",
    "negative_prompt": "",
    "num_inference_steps": 50,
    "guidance_scale": 7.5,
    "seed": 1,
    "gpu": 0,
    "sampling_method": "ddim",
    "model": "sd",
    "sd_path": "stabilityai/stable-diffusion-2-base",
    "ref_attention_end": 0.2,
    "mvd_end": 0.8,
    "save_top_dir": "./eval_outputs",
    "tag": "wide_image",
    "save_dir_now": true,
    "log_step": 10,
    "eval_w": [
        0,
        10,
        20,
        30,
        40,
        50,
        60,
        70
    ],
    "eval_h": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
    ],
    "initialize_xt_from_zt": false,
    "window_stride": 8,
    "latent_instance_size": 64,
    "rgb_instance_size": 512,
    "panorama_height": 512,
    "panorama_width": 3072,
    "eval_pos": [
        "1295",
        "488",
        "147",
        "852",
        "1046",
        "343",
        "1204",
        "1070"
    ]
}